pipeline{
  agent any
  stages{
    stage("Build"){
      steps{
        echo "Build Stage"
      }
    }
    
    stage("Deploy"){
      steps{
        echo "Deploy Stage"
      }
    }
    
    stage("Test"){
      steps{
        echo "Test Stage"
      }
    }
    
  }
}
